// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG0C2CdZHGASz8gVM4CpbXtIHsPdS6wsI',
    appId: '1:1010957724148:web:2324c62c89b7d82ea571a1',
    messagingSenderId: '1010957724148',
    projectId: 'notebot-658a8',
    authDomain: 'notebot-658a8.firebaseapp.com',
    storageBucket: 'notebot-658a8.appspot.com',
    measurementId: 'G-NN463VM6QT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYfdvofEi7QBEXwjhGaCLfPAenW0ufQI',
    appId: '1:1010957724148:ios:40a53b7cfe8dea35a571a1',
    messagingSenderId: '1010957724148',
    projectId: 'notebot-658a8',
    storageBucket: 'notebot-658a8.appspot.com',
    androidClientId: '1010957724148-pqs7qmg0rqep0cdl3vv6bnfdtr7uc1sk.apps.googleusercontent.com',
    iosClientId: '1010957724148-mu932tqv2c9f48ifn03fgum1ojnovcct.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYfdvofEi7QBEXwjhGaCLfPAenW0ufQI',
    appId: '1:1010957724148:ios:40a53b7cfe8dea35a571a1',
    messagingSenderId: '1010957724148',
    projectId: 'notebot-658a8',
    storageBucket: 'notebot-658a8.appspot.com',
    androidClientId: '1010957724148-pqs7qmg0rqep0cdl3vv6bnfdtr7uc1sk.apps.googleusercontent.com',
    iosClientId: '1010957724148-mu932tqv2c9f48ifn03fgum1ojnovcct.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG0C2CdZHGASz8gVM4CpbXtIHsPdS6wsI',
    appId: '1:1010957724148:web:1e2d21469aab5cf4a571a1',
    messagingSenderId: '1010957724148',
    projectId: 'notebot-658a8',
    authDomain: 'notebot-658a8.firebaseapp.com',
    storageBucket: 'notebot-658a8.appspot.com',
    measurementId: 'G-SVL8QRCGW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7lEBG85YB3BBInwrC7hq0Mk9JGbyy6o',
    appId: '1:1010957724148:android:33c796b300f08b2ca571a1',
    messagingSenderId: '1010957724148',
    projectId: 'notebot-658a8',
    storageBucket: 'notebot-658a8.appspot.com',
  );

}